"""Registry of external data sources for ThermoTwin-3D.

Single source of truth for *where* every dataset lives, its licence, and whether
it is gated behind a registration/EULA we cannot complete automatically. The
download CLI (``scripts/download_data.py``) consumes this registry; nothing here
performs IO so it is cheap to import and easy to test.

Roles (see ``docs/datasets.md``):
  * real thermal + geometry   -> validation / calibration  (TUM2TWIN, TBBR)
  * geometry corpus           -> scan realism + FEM substrate (DOE, ScanNet++, ...)
  * physics ground truth      -> we generate it (not listed here)

Critical-path datasets (DOE reference buildings, TBBR) are *open* and scripted.
Gated datasets carry a ``registration_url``; their downloader writes a SOURCE.md
placeholder instead of fetching, so a human can complete the EULA later and the
same command then just works.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum

__all__ = ["Role", "RemoteFile", "DataSource", "SOURCES", "get_source"]


class Role(str, Enum):
    REAL_THERMAL = "real_thermal"  # measured thermal + geometry (validation)
    GEOMETRY = "geometry"  # as-built / envelope geometry corpus
    PHYSICS_GT = "physics_gt"  # generated by us


# Canonical EnergyPlus weather file used with the DOE reference buildings.
_EP = "https://raw.githubusercontent.com/NREL/EnergyPlus/develop"

# The 16 DOE Commercial Reference Building prototypes (post-2004), Chicago climate.
# Variant files (ReturnReset / JSON_Outputs / OutputControl) are intentionally excluded.
_DOE_TYPES = [
    "SmallOffice",
    "MediumOffice",
    "LargeOffice",
    "Stand-aloneRetail",
    "StripMall",
    "PrimarySchool",
    "SecondarySchool",
    "SmallHotel",
    "LargeHotel",
    "Hospital",
    "OutPatient",
    "Warehouse",
    "QuickServiceRestaurant",
    "FullServiceRestaurant",
    "SuperMarket",
    "MidriseApartment",
]


@dataclass(frozen=True)
class RemoteFile:
    """One downloadable artefact: ``url`` -> ``<dataset_root>/relpath``."""

    url: str
    relpath: str
    size_bytes: int | None = None  # best-known size, for budgeting; None if unknown


@dataclass(frozen=True)
class DataSource:
    """A dataset we depend on.

    A *gated* source has a ``registration_url`` and (usually) no scriptable files;
    the downloader writes a SOURCE.md placeholder for it. An *open* source carries
    a concrete ``files`` list (or a ``sample`` subset for cheap critical-path pulls).
    """

    key: str
    title: str
    role: Role
    license: str
    homepage: str
    gated: bool = False
    registration_url: str | None = None
    files: list[RemoteFile] = field(default_factory=list)
    sample: list[RemoteFile] = field(default_factory=list)  # cheap subset, if any
    notes: str = ""

    @property
    def is_open(self) -> bool:
        return not self.gated


def _doe_reference_buildings() -> DataSource:
    files = [
        RemoteFile(
            url=f"{_EP}/testfiles/RefBldg{t}New2004_Chicago.idf",
            relpath=f"idf/RefBldg{t}New2004_Chicago.idf",
        )
        for t in _DOE_TYPES
    ]
    # Chicago O'Hare TMY3 — the climate these prototypes are authored for.
    files.append(
        RemoteFile(
            url=f"{_EP}/weather/USA_IL_Chicago-OHare.Intl.AP.725300_TMY3.epw",
            relpath="weather/USA_IL_Chicago-OHare.Intl.AP.725300_TMY3.epw",
        )
    )
    return DataSource(
        key="doe",
        title="DOE Commercial Reference Buildings (EnergyPlus prototypes)",
        role=Role.GEOMETRY,
        license="Public domain (US DOE / NREL EnergyPlus)",
        homepage="https://www.energy.gov/eere/buildings/commercial-reference-buildings",
        files=files,
        notes="16 building types, Chicago climate; full envelope construction layers. "
        "Geometry + material substrate for synthetic FEM ground truth (Block 1).",
    )


def _tbbr() -> DataSource:
    rec = "https://zenodo.org/records/6517768/files"
    coco = [
        RemoteFile(
            f"{rec}/Flug1_100-104Media_coco.json?download=1",
            "Flug1_100-104Media_coco.json",
            1_700_000,
        ),
        RemoteFile(
            f"{rec}/Flug1_105Media_coco.json?download=1", "Flug1_105Media_coco.json", 400_000
        ),
    ]
    flights = {
        "Flug1_100": 6_014_000_000,
        "Flug1_101": 13_918_000_000,
        "Flug1_102": 13_671_000_000,
        "Flug1_103": 14_273_000_000,
        "Flug1_104": 14_737_000_000,
        "Flug1_105": 5_929_000_000,  # test flight
    }
    full = coco + [
        RemoteFile(f"{rec}/{name}.tar.zst?download=1", f"{name}.tar.zst", sz)
        for name, sz in flights.items()
    ]
    # Critical-path sample: annotations + the smallest flight (~6 GB) to develop against.
    sample = coco + [
        RemoteFile(
            f"{rec}/Flug1_100.tar.zst?download=1", "Flug1_100.tar.zst", flights["Flug1_100"]
        ),
    ]
    return DataSource(
        key="tbbr",
        title="Thermal Bridges on Building Rooftops (TBBRv2)",
        role=Role.REAL_THERMAL,
        license="CC-BY-4.0",
        homepage="https://doi.org/10.5281/zenodo.6517768",
        files=full,
        sample=sample,
        notes="926 UAV scenes (RGB+thermal+height), 6927 thermal-bridge annotations. "
        "Paper: Mayer et al., Automation in Construction 2022 "
        "(10.1016/j.autcon.2022.104690) — our target venue. "
        "Code: github.com/Helmholtz-AI-Energy/TBBRDet. Full set ~68.5 GB.",
    )


# --- Gated geometry / thermal corpora (registration required; we stub these) ---


def _gated(key, title, role, license, homepage, registration_url, notes) -> DataSource:
    return DataSource(
        key=key,
        title=title,
        role=role,
        license=license,
        homepage=homepage,
        gated=True,
        registration_url=registration_url,
        notes=notes,
    )


SOURCES: dict[str, DataSource] = {
    s.key: s
    for s in [
        _doe_reference_buildings(),
        _tbbr(),
        _gated(
            "tum2twin",
            "TUM2TWIN (MLS + LoD2/3 CityGML + TIR thermal point clouds)",
            Role.REAL_THERMAL,
            "Custom research licence — verify redistribution terms",
            "https://tum2t.win/",
            "https://tum2t.win/",
            "Premier real-building thermal validation anchor (Block 2). Register on the "
            "portal; drop the access URL/token into SOURCE.md.",
        ),
        _gated(
            "scannetpp",
            "ScanNet++ (high-fidelity indoor as-built reconstructions)",
            Role.GEOMETRY,
            "ScanNet++ Terms of Use (signed)",
            "https://kaldir.vc.in.tum.de/scannetpp/",
            "https://kaldir.vc.in.tum.de/scannetpp/",
            "~1 TB full. Sign ToU, receive download script + token. Realistic "
            "reconstructed geometry with defects.",
        ),
        _gated(
            "matterport3d",
            "Matterport3D (indoor building reconstructions)",
            Role.GEOMETRY,
            "Matterport3D Terms of Use (signed, emailed)",
            "https://niessner.github.io/Matterport/",
            "https://niessner.github.io/Matterport/",
            "Email signed ToU to receive download_mp.py. ~1 TB full.",
        ),
        _gated(
            "structured3d",
            "Structured3D (structured layout geometry)",
            Role.GEOMETRY,
            "Structured3D agreement",
            "https://structured3d-dataset.org/",
            "https://structured3d-dataset.org/",
            "Layout priors / structured geometry. Requires signed agreement form.",
        ),
        _gated(
            "building3d",
            "Building3D (real ALS point cloud <-> roof wireframe/mesh)",
            Role.GEOMETRY,
            "Building3D research licence",
            "https://building3d.ucalgary.ca/",
            "https://building3d.ucalgary.ca/",
            "Real envelope geometry at scale. Registration required.",
        ),
    ]
}


def get_source(key: str) -> DataSource:
    try:
        return SOURCES[key]
    except KeyError:
        raise KeyError(f"unknown dataset {key!r}; known: {', '.join(sorted(SOURCES))}") from None
